rofl:
  network: mainnet  # Options: mainnet, testnet
log:
  format: JSON
  level: info       # Log level (debug, info, warn, error)
  file: ""          # Log file path (empty for stdout)
appd:
  signing_key_id: erc8004v1-signing-key
  mock: false # Set to true for testing with mocked Appd
#  mock_signing_key: private_key_outside_tee
validation_networks:
  ethereum-sepolia:
    rpc: wss://sepolia.infura.io/ws/v3/${API_KEY}
    identity_registry: "0x7177a6867296406881E20d6647232314736Dd09A"
    validation_registry: "0x662b40A526cb4017d947e71eAF6753BF3eeE66d8"
  base-sepolia:
    rpc: wss://base-sepolia.infura.io/ws/v3/${API_KEY}
    identity_registry: "0x7177a6867296406881E20d6647232314736Dd09A"
    validation_registry: "0x662b40A526cb4017d947e71eAF6753BF3eeE66d8"
  optimism-sepolia:
    rpc: wss://optimism-sepolia.infura.io/ws/v3/${API_KEY}
    identity_registry: "0x7177a6867296406881E20d6647232314736Dd09A"
    validation_registry: "0x662b40A526cb4017d947e71eAF6753BF3eeE66d8"
