[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
ffi = true
viaIR = true

[dependencies]
"@oasisprotocol-sapphire-foundry" = "0.1.2"
"@oasisprotocol-sapphire-contracts" = "0.2.15"
"@openzeppelin-contracts" = "5.5.0-rc.1"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
